apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: swisnap-agent-ds
  labels:
    daemon: swisnap-agent-ds
spec:
  selector:
    matchLabels:
      daemon: swisnap-agent-ds
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: swisnap-agent-ds
      labels:
        daemon: swisnap-agent-ds
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: swisnap-agent-ds
        image: solarwinds/solarwinds-snap-agent-docker:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: probe
            containerPort: 21413
            protocol: TCP
        env:
          - name: APPOPTICS_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: APPOPTICS_TOKEN
            valueFrom:
              secretKeyRef:
                name: appoptics-token
                key: APPOPTICS_TOKEN
          - name: SWISNAP_ENABLE_APACHE
            value: "false"
          - name: SWISNAP_ENABLE_DOCKER
            value: "true"
          - name: SWISNAP_ENABLE_ELASTICSEARCH
            value: "false"
          - name: SWISNAP_ENABLE_KUBERNETES
            value: "false"
          - name: SWISNAP_ENABLE_MESOS
            value: "false"
          - name: SWISNAP_ENABLE_MONGODB
            value: "false"
          - name: SWISNAP_ENABLE_MYSQL
            value: "false"
          - name: SWISNAP_ENABLE_RABBITMQ
            value: "false"
          - name: SWISNAP_ENABLE_STATSD
            value: "false"
          - name: SWISNAP_ENABLE_ZOOKEEPER
            value: "false"
          - name: SWISNAP_DISABLE_HOSTAGENT
            value: "false"
          - name: SWISNAP_DISABLE_PROCESSES
            value: "false"
          - name: SWISNAP_SECURE
            value: "false"    
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: cgroup
            mountPath: /sys/fs/cgroup
        livenessProbe:
          httpGet:
            path: /v1/plugins
            port: 21413
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /v1/plugins
            port: 21413
          initialDelaySeconds: 10
          timeoutSeconds: 5
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
